### ISSUE TITLE
Add bower support

### ISSUE THREAD

**Issue by webdevsuperfast** [kgcreative/neat-omega#2]
Hi,

Neat fix for clearing floats in the new Bourbon Neat. Question, will you add bower support any time soon?

Thanks!

**Comment by kgcreative** [comment]
@webdevsuperfast - 
I just published v2.0.9, which includes expanded documentation and bower support. Please let me know if you have any questions or run into issues.

**Comment by webdevsuperfast** [comment]
Thanks!
