### ISSUE TITLE
Add neat-omega to rubygems?

### ISSUE THREAD

**Issue by whmii** [kgcreative/neat-omega#3]
Howdy,

I posted another extension for Neat over at https://github.com/whmii/neat-class-generator

It also has a rubygems implementation that you could probably copy for this repo if you want (since I copied your npm/bower implementation 😉). 

✌️

**Comment by kgcreative** [comment]
@whmii - Time to learn Ruby!

**Comment by kgcreative** [comment]
@whmii - check out https://rubygems.org/gems/neat-omega and let me know if it works!

**Comment by whmii** [comment]
Tested 

```scss
.foo {
  @include nth-alpha(4n+1);
}
```

on https://github.com/thoughtbot/neat.bourbon.io after bundling and importing and code compiled and generated 

```css 
.foo:nth-of-type(5n) {
  clear: left; }
```

👍

**Comment by kgcreative** [comment]
@whmii Thanks! I'll go ahead and close this. Feel free to reopen if any issues arise.
